language: julia
os:
    - linux
julia:
    - release
    - nightly
notifications:
    - email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --check-bounds-yes -e 'Pkg.clone(pwd()); Pkg.build("Scattering"); Pkg.test("Scattering"; coverage=true)''
after_success:
    - julia -e 'cd(Pkg.dir("Scattering")); Pkg.add("Scattering"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
